import { component$ } from "@builder.io/qwik";
import type { IconProps } from "../utils";

export const IconApps = component$((props: IconProps) => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="512"
      height="512"
      viewBox="0 0 512 512"
      stroke="currentColor"
      fill="currentColor"
      class={props.class}
    >
      <rect
        x="64"
        y="64"
        width="80"
        height="80"
        rx="40"
        ry="40"
        style="fill:none;stroke-miterlimit:10;stroke-width:32px"
      />
      <rect
        x="216"
        y="64"
        width="80"
        height="80"
        rx="40"
        ry="40"
        style="fill:none;stroke-miterlimit:10;stroke-width:32px"
      />
      <rect
        x="368"
        y="64"
        width="80"
        height="80"
        rx="40"
        ry="40"
        style="fill:none;stroke-miterlimit:10;stroke-width:32px"
      />
      <rect
        x="64"
        y="216"
        width="80"
        height="80"
        rx="40"
        ry="40"
        style="fill:none;stroke-miterlimit:10;stroke-width:32px"
      />
      <rect
        x="216"
        y="216"
        width="80"
        height="80"
        rx="40"
        ry="40"
        style="fill:none;stroke-miterlimit:10;stroke-width:32px"
      />
      <rect
        x="368"
        y="216"
        width="80"
        height="80"
        rx="40"
        ry="40"
        style="fill:none;stroke-miterlimit:10;stroke-width:32px"
      />
      <rect
        x="64"
        y="368"
        width="80"
        height="80"
        rx="40"
        ry="40"
        style="fill:none;stroke-miterlimit:10;stroke-width:32px"
      />
      <rect
        x="216"
        y="368"
        width="80"
        height="80"
        rx="40"
        ry="40"
        style="fill:none;stroke-miterlimit:10;stroke-width:32px"
      />
      <rect
        x="368"
        y="368"
        width="80"
        height="80"
        rx="40"
        ry="40"
        style="fill:none;stroke-miterlimit:10;stroke-width:32px"
      />
    </svg>
  );
});
